- hosts: mongodbsvrs
  roles:
      - { role: "mongodb_linux" }
      - { role: "mongodb_install" }
      - { role: "mongodb_mongod" }

  tasks:

    - name: Initialise MongoDB Replicaset rs0
      community.mongodb.mongodb_replicaset:
        login_database: "admin"
        login_host: localhost
        replica_set: "rs0"
        members:
          - "mongodb1"
          - "mongodb2"
          - "mongodb3"
      when: ansible_hostname == "mongodb1"
      register: repl

    - name: Ensure replicaset has reached a converged state
      community.mongodb.mongodb_status:
        replica_set: "rs0"
        poll: 10
        interval: 10
      when: repl.changed == True

    - name: Import mongodb_auth role
      include_role:
        name: mongodb_auth
      vars:
        mongod_host: "127.0.0.1"
        mongodb_admin_pwd: "admin"
      when: ansible_hostname == "mongodb1"