- hosts: mongodbsvrs
  roles:
      - { role: "mongodb_linux" }
      - { role: "mongodb_install" }
      - { role: "mongodb_mongod" }

  tasks:

    - name: Initialise MongoDB Replicaset rs0
      mongodb_replicaset:
        login_database: "admin"
        login_host: localhost
        replica_set: "rs0"
        members:
          - "ansible-1"
          - "ansible-2"
          - "ansible-3"
      when: ansible_hostname == "mongodb-ansible-1"
      register: repl

    - name: Import mongodb_auth role
      include_role:
        name: mongodb_auth
      vars:
        mongod_host: "127.0.0.1"
        mongodb_admin_pwd: "admin"
      when: ansible_hostname == "mongodb-ansible-1"
