- hosts: configsvrs
  vars_files:
    - vars/default.yml

  tasks:
    - name: Confiure Operating System
      include_role:
        name: mongodb_linux

    - name: Install MongoDB Packages
      include_role:
        name: mongodb_install

    - name: Setup of Mongos Service
      include_role:
        name: mongodb_mongos

    - name: Initialise MongoDB Replicaset Authentication
      include_role:
        name: mongodb_auth
      when: ansible_hostname == mongodb_master