- hosts: mongodbsvrs
  vars:
    cluster_type: replica_set
    mongodb_port: 27017

  tasks:
    - name: Check out the primary node
      shell: chdir=/opt/OmniMongoDB/ansible mongo --port {{ mongodb_port }} --eval 'db.hello().primary'
      register: primary

    - name: Restore full backup replica set data automatically
      include_role:
        name: mongodb_restore
      vars:
        primary_host: "mongodb-{{ primary.stdout_lines[-1] | regex_replace(':27017') }}"
      when: ansible_hostname == primary_host
