- hosts: configsvrs
  vars:
    - configsvr_master: mongodb-ansible-4
    - configsvr_repl_set_name: cfg
  vars_files:
  - vars/default.yml

  tasks:
    - name: Confiure Operating System
      include_role:
        name: mongodb_linux

    - name: Install MongoDB Packages
      include_role:
        name: mongodb_install

    - name: Setup of Configsvr Service
      include_role:
        name: mongodb_configsvr

    - name: Initialise Configsvr Replicaset
      mongodb_replicaset:
        login_database: "admin"
        login_host: localhost
        login_port: 27019
        replica_set: "{{ configsvr_repl_set_name }}"
        members:
          - "ansible-4:27019"
          - "ansible-5:27019"
          - "ansible-6:27019"
      when: ansible_hostname == configsvr_master
      register: repl

    - name: Initialise Configsvr Replicaset Authentication
      include_role:
        name: mongodb_auth
      vars:
        mongodb_port: 27019
        mongodb_admin_user: admin
        mongodb_admin_pwd: admin
        mongodb_admin_roles: root
      when: ansible_hostname == configsvr_master

- hosts: mongodbsvrs
  vars:
    - master_shard_1: mongodb-ansible-1

  tasks:
    - name: Confiure Operating System
      include_role:
        name: mongodb_linux

    - name: Install MongoDB Packages
      include_role:
        name: mongodb_install

    - name: Setup of MongoDB Service
      include_role:
        name: mongodb_mongod
      vars:
        - sharding: true

    - name: Initialise MongoDB Replicaset
      mongodb_replicaset:
        login_database: "admin"
        login_host: localhost
        replica_set: "{{ repl_set_name }}"
        members: "{{ replica_set_members }}"
      when: ansible_hostname == mongodb_master
      register: repl

    - debug:
        msg: "{{ repl }}"

    - name: Initialise MongoDB Replicaset Authentication
      include_role:
        name: mongodb_auth
      when: ansible_hostname == mongodb_master

- hosts: mongos
  tasks:
    - name: Confiure Operating System
      include_role:
        name: mongodb_linux

    - name: Install MongoDB Packages
      include_role:
        name: mongodb_install

    - name: Setup of Mongos Service and Add Replicaset Into Shard
      include_role:
        name: mongodb_mongos