---
# task file for mongodb_config

- name: Ensure db_path dir exists
  file:
    path: "{{ db_path }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"

- name: Ensure log_path dir exists
  file:
    path: "{{ log_path }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"

- name: Copy config file
  template:
    src: "{{ configsvr_config_template }}"
    dest: /etc/mongod_cfg.conf
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  notify:
    - Restart mongod service

- name: Copy keyfile to host
  copy:
    content: |
      {{ openssl_keyfile_content }}
    dest: /etc/keyfile
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0400
  when: authorization == "enabled"
  notify:
    - Restart mongod service

- name: Start mongod service
  service:
    name: "{{ mongod_service }}"
    state: started
    enabled: yes