---
# task file for mongodb depolyment

- name: Create dbpath
  file:
    path: /data
    state: directory
    owner: monogd
    group: mongod

- name: Create log directory
  file:
    path: /data/log
    state: directory
    owner: mongod
    group: mongod