---
# task file for linux configuration

- name: Include OS-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        - main.yml

- name: Create mongodb files
  file:
    path: /opt/OmniMongoDB/mongodb
    state: directory
    owner: root
    group: root

- name: Create mongod Group
  group:
    name: mongod
    system: yes

- name: Create mongod User
  user:
    name: mongod
    comment: mongodb
    group: mongod
    shell: /bin/bash
    home: /opt/OmniMongoDB
    system: yes
    create_home: no
    non_unique: yes

- name: Copy mongodb package
  unarchive:
    src: mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}.tgz
    dest: /opt/OmniMongoDB
    copy: yes

- name: Create mongodb symlink
  file:
    src: /opt/OmniMongoDB/mongodb
    dest: /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}

- name: Setup mongod service
  copy:
    src: mongod.service
    dest: /usr/lib/systemd/system/mongod.service
    owner: root
    group: root

- name: Reload systemd
  systemd:
    daemon_reexec: yes