---
# task file for mongodb installation

- name: Include OS-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        - main.yml

- name: Create mongod Group
  group:
    name: mongod
    system: yes

- name: Create mongod User
  user:
    name: mongod
    comment: mongodb
    group: mongod
    shell: /bin/bash
    home: /opt/OmniMongoDB
    system: yes
    create_home: no
    non_unique: yes

- name: Create mongod dir
  file:
    path: /opt/OmniMongoDB/ansible
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"

- name: Create mongod backup dir
  file:
    path: /opt/OmniMongoDB/backup
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"

- name: Setup mongod packages and service
  include_tasks: "setup_pkg_{{ ansible_facts.os_family }}.yml"

- name: Create mongodb binary symlink
  file:
    src: /opt/OmniMongoDB/mongodb/bin/{{ item }}
    dest: /usr/bin/{{ item }}
    state: link
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  with_items:
    - bsondump
    - install_compass
    - mongo
    - mongod
    - mongodump
    - mongoexport
    - mongofiles
    - mongoimport
    - mongorestore
    - mongos
    - mongotop

- name: Reload systemd
  systemd:
    daemon_reexec: yes