---
# task file for mongodb installation

- name: Include OS-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        - main.yml

- name: Install required packages
  yum:
    name: "{{ yum_packages }}"
    state: present

- name: Create mongod dir
  file:
    path: /opt/OmniMongoDB/ansible
    state: directory
    owner: root
    group: root

- name: Create mongod backup dir
  file:
    path: /opt/OmniMongoDB/backup
    state: directory
    owner: root
    group: root

- name: Create mongod Group
  group:
    name: mongod
    system: yes

- name: Create mongod User
  user:
    name: mongod
    comment: mongodb
    group: mongod
    shell: /bin/bash
    home: /opt/OmniMongoDB
    system: yes
    create_home: no
    non_unique: yes

- name: Copy mongodb package
  unarchive:
    src: mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}.tgz
    dest: /opt/OmniMongoDB
    copy: yes

- name: Create mongodb package symlink
  file:
    src: /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}
    dest: /opt/OmniMongoDB/mongodb
    state: link

- name: Create mongodb binary symlink
  file:
    src: /opt/OmniMongoDB/mongodb/bin/{{ item }}
    dest: /usr/bin/{{ item }}
    state: link
  with_items:
    - bsondump
    - install_compass
    - mongo
    - mongod
    - mongodump
    - mongoexport
    - mongofiles
    - mongoimport
    - mongorestore
    - mongos
    - mongotop

- name: Setup mongod service
  copy:
    src: mongod.service
    dest: /usr/lib/systemd/system/mongod.service
    owner: root
    group: root

- name: Reload systemd
  systemd:
    daemon_reexec: yes