---
# task file for mongodb installation

- name: Include OS-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        - main.yml

- name: Install required packages
  yum:
    name:
      - openssl
      - rpm-libs
      - wget
      - vim
      - pymongo
    state: present

- name: Create mongod dir
  file:
    path: /opt/OmniMongoDB
    state: directory
    owner: root
    group: root

- name: Create mongod Group
  group:
    name: mongod
    system: yes

- name: Create mongod User
  user:
    name: mongod
    comment: mongodb
    group: mongod
    shell: /bin/bash
    home: /opt/OmniMongoDB
    system: yes
    create_home: no
    non_unique: yes

- name: Copy mongodb package
  unarchive:
    src: mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}.tgz
    dest: /opt/OmniMongoDB
    copy: yes

- name: Create mongodb symlink
  file:
    src: /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}
    dest: /opt/OmniMongoDB/mongodb
    state: link

- name: Copy mongodb bin to /usr/bin
  copy:
    src: "{{ item }}"
    dest: /usr/bin/
    owner: root
    group: root
    remote_src: yes
  with_items:
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/bsondump
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/install_compass
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongo
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongod
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongodump
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongoexport
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongofiles
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongoimport
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongorestore
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongos
    - /opt/OmniMongoDB/mongodb-linux-x86_64-rhel70-{{  mongodb_version  }}/bin/mongotop
  
- name: Setup mongod service
  copy:
    src: mongod.service
    dest: /usr/lib/systemd/system/mongod.service
    owner: root
    group: root

- name: Reload systemd
  systemd:
    daemon_reexec: yes