---

- name: Include OS-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        - main.yml

- name: Ensure mongod and pyyaml packages are installed
  package:
    name:
      # pyyaml is used to validate yaml files on change
      - "{{ pyyaml_package }}"
    state: present
  register: _pkg
  until: _pkg is succeeded
  retries: 5

- name: Warn about default credentials
  when: mongodb_admin_pwd == mongodb_default_admin_pwd
  debug:
    msg: "[WARNING] Using default admin credentials for mongodb admin account! Please change them!"

- name: Add mongo admin user with localhost exception
  script: initAdminUser.sh {{ mongod_port }} {{ mongodb_admin_user }} {{ mongodb_admin_pwd }}

- name: Enable security section in mongod.conf
  lineinfile:
    path: /etc/mongod.conf
    regexp: |-
      ^[#'"\s]*security['"]?\s*:
    line: 'security:'
    validate: |
      {{ mongodb_python }} -c '
      import yaml, io
      if "security" not in yaml.safe_load(io.open("%s")):
          exit(1)
      '
- name: Enable authentication in mongod.conf
  lineinfile:
    path: /etc/mongod.conf
    insertafter: '^security:'
    # two space indentation (the default) assumed
    line: '  authorization: {{ authorization }}'
    regexp: |-
      ^[#'"\s]+authorization['"]?\s*:
    validate: |
      {{ mongodb_python }} -c '
      import yaml, io
      if yaml.safe_load(io.open("%s"))["security"]["authorization"] != "{{ authorization }}":
          exit(1)
      '
  register: _enable_mongo_auth

# # This is a task instead of a handler so we can add users right away
# - name: Restart mongodb to enable auth before adding additional users
#   # This allows us to safely assume auth is already enabled when adding more users
#   when: _enable_mongo_auth is changed
#   service:
#     name: mongod
#     state: restarted

# - name: Add additional mongo users
#   include_tasks: mongodb_auth_user.yml
#   loop: "{{ mongodb_users }}"
#   loop_control:
#     loop_var: _mongodb_user
#   # using loop_control: label does not obscure the password in output for verbosity > 1
#   # So, loop over an include where the task name will include the username + db, but the loop var won't print out.
#   no_log: yes