---

- name: Include Restore-specific vars
  include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        - main.yml

- name: Copy the scripts to data source host
  template:
    src: "{{ item }}"
    dest: /opt/OmniMongoDB/ansible/{{ item | basename | regex_replace('\.j2$', '') }}
  with_items:
    - addSecondary.js.j2
    - rmSecondary.js.j2
    - mongorestore.sh.j2
    - mongodump_oplog.sh.j2

- name: Remove secondary nodes from replica set
  shell: chdir=/opt/OmniMongoDB/ansible mongo --port {{ mongodb_port }} rmSecondary.js
    
- name: Obtain backup MongoDB database files
  unarchive: 
    src: "{{ backup_path }}/{{ target_backup_date }}_mongodb_backup.tar.gz"
    dest: /opt/OmniMongoDB/backup
    copy: yes

- name: Dump oplog from primary node
  shell: chdir=/opt/OmniMongoDB/ansible /bin/bash mongodump_oplog.sh

- name: Copy oplog to backup directory
  copy:
    src: /opt/OmniMongoDB/backup/{{ ansible_date_time.date }}_mongodb_oplog/oplog.rs.bson
    dest: /opt/OmniMongoDB/backup/{{ target_backup_date }}_mongodb_backup/oplog.bson
    remote_src: true

- name: Restore data to primary with mongorestore
  shell: chdir=/opt/OmniMongoDB/ansible /bin/bash mongorestore.sh

- name: Add secondary nodes from replica set
  shell: chdir=/opt/OmniMongoDB/ansible mongo --port {{ mongodb_port }} addSecondary.js