---

- name: Copy keyfile to host
  copy:
    content: |
      {{ openssl_keyfile_content }}
    dest: /etc/keyfile
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0400
  notify:
    - Restart mongos service

- name: Ensure /opt/OmniMongoDB/ansible directory exists
  file:
    path: /opt/OmniMongoDB/ansible
    state: directory
    recurse: yes

- name: Ensure mongos add shard script exists
  template:
    src: addShard.js.j2
    dest: /opt/OmniMongoDB/ansible/addShard.js
    mode: 0755

- name: Ensure mongos service pre start script exists
  template:
    src: mongos_pre.sh.j2
    dest: /opt/OmniMongoDB/ansible/mongos_pre.sh
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0755

- name: Ensure mongos.service file exists
  template:
    src: mongos.service.j2
    dest: /etc/systemd/system/mongos.service
    owner: root
    group: root
  register: sysd

- name: Run systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when: sysd is changed

- name: Ensure mongos.conf file exists
  template:
    src: "{{ mongos_config_template }}"
    dest: /etc/mongos.conf
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  notify:
    - Restart mongos service

- name: Start mongos service
  service:
    name: "{{ mongos_service }}"
    state: started
    enabled: yes

- pause:
    seconds: 30

- name: Add replica set into shard cluster
  shell:  chdir=/opt/OmniMongoDB/ansible mongo --port {{ mongos_port }} addShard.js